language: ruby
cache: bundler
rvm:
  - 2.1.2

env:
#  - DB=sqlite
#  - DB=mysql
  - DB=postgresql

#before_script:
#  - sudo apt-get install graphicsmagick
#  - mysql -e 'create database chromotype_test'
#  - psql -c 'create database chromotype_test' -U postgres

script:
  - bundle exec rake db:drop
  - bundle exec rake db:create
  - bundle exec rake db:migrate

deploy:
  provider: heroku
  api_key:
    secure: 334d93d0-a30a-4df0-b183-c529c0b4caad
  app: tranquil-gorge-23262
  strategy: git
  run:
    - "rake db:migrate"
script:
  - bundle exec rake