language: ruby
cache: bundler
rvm:
  - 2.1.2

env:
  - DB=sqlite
#  - DB=mysql
#  - DB=postgresql

before_script:
  - sudo apt-get install graphicsmagick
#  - mysql -e 'create database chromotype_test'
  - psql -c 'create database chromotype_test' -U postgres

#script:
#  - rake